version: "3.6"

networks:
  net:
    driver: bridge

services:

  data11:
    image: mongo:3.6
    container_name: data11
    command: mongod --shardsvr --replSet data1rs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  data12:
    image: mongo:3.6
    container_name: data12
    command: mongod --shardsvr --replSet data1rs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  data13:
    image: mongo:3.6
    container_name: data13
    command: mongod --shardsvr --replSet data1rs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  data21:
    image: mongo:3.6
    container_name: data21
    command: mongod --shardsvr --replSet data2rs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  data22:
    image: mongo:3.6
    container_name: data22
    command: mongod --shardsvr --replSet data2rs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  data23:
    image: mongo:3.6
    container_name: data23
    command: mongod --shardsvr --replSet data2rs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  cfg1:
    image: mongo:3.6
    container_name: cfg1
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  cfg2:
    image: mongo:3.6
    container_name: cfg2
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  cfg3:
    image: mongo:3.6
    container_name: cfg3
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  mongos1:
    image: mongo:3.6
    container_name: mongos1
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  mongos2:
    image: mongo:3.6
    container_name: mongos2
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017 --bind_ip_all
    expose:
      - 27017
    networks:
      - net

  bootstrap:
    build:
      context: bootstrap/
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN
    container_name: mongo-bootstrap
    command:
      - '--dataSet=data1rs/data11:27017,data12:27017,data13:27017'
      - '--dataSet=data2rs/data21:27017,data22:27017,data23:27017'
      - '--configSet=cfgrs/cfg1:27017,cfg2:27017,cfg3:27017'
      - '--mongos=mongos1:27017,mongos2:27017'
    networks:
      - net
